FROM golang:1.27.1-bookworm AS toolchain
FROM baseguard:local
USER root
COPY --from=toolchain /usr/local/go /usr/local/go
ENV PATH=/usr/local/go/bin:$PATH GOCACHE=/tmp/go-cache GOMODCACHE=/go/pkg/mod
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
ENTRYPOINT ["go", "test", "./...", "-count=1", "-v"]
